In [14]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
np.set_printoptions(suppress=True) # pedimos a numpy que no muestre los numeros pequenos de punto flotante

In [15]:
# La Pseudoinversa de Moore-Penrose es una aplicacion directa de SVD, que puede ser utilizada para resolver un 
# sistema de ecuaciones, ese que ya viste en clases anteriores. Recordemos que un sistema de ecuaciones lineales
# puede ser expresado en forma matricial

In [16]:
# Pero en el caso que la matriz no sea cuadrada, o que el conjunto de ecuaciones tenga 0 o muchas soluciones, o sea
# que la matriz no tenga inversa y por lo tanto no podamos resolver el sitema de ecuaciones, es aqui donde el uso
# de la Pseudoinversa puede ayudarnos

# nuestro sistema es A x = b , si existe la inversa podemos hacer x = A_inv b

# Pero si no existe podemos tratar de encontrar otra matriz, llamemosla A_pse tal que A * A_pse se aproxime a la Id

# Como hablamos de aproximarnos, entonces pedimos que A_pse minimice la norma (A * A_pse - Id)

# Una posible pseudo inversa es A_pse = V D_pse U.T donde V,D,U son los obtenidos al calcular la descomposicion SVD

In [17]:
# Veamos un ejemplo, escribamos A una matriz no cuadrada y por lo tanto sin inversa

A = np.array([[7, 2], [3, 4], [5, 3]])
U, D, V = np.linalg.svd(A)

D_pse = np.zeros((A.shape[0], A.shape[1])).T
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))

A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]


In [18]:
# Validemos con la funcion de numpy pinv() que la pseudoinversa calculada es correcta
print(np.linalg.pinv(A))

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]


In [20]:
# Veamos si es una "inversa"
print(A_pse.dot(A))

# Aqui vale señalar que el resultado no es este exactamente, los numeros estan redondeados a la precision de float

[[1. 0.]
 [0. 1.]]


In [23]:
# si descativamos la opcion de formato automatico
np.set_printoptions(suppress=False) 

In [24]:
print(A_pse.dot(A))

[[1.00000000e+00 2.63677968e-16]
 [5.55111512e-17 1.00000000e+00]]


In [25]:
# Observemos una diferencia con las inversas reales, las que si existen
# Sabemos que A * A_inv = A_inv * A = Id
# Con la pseudoinversa eso no ocurre, entones A_pse * A != A * A_pse

print(A.dot(A_pse))

[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


In [26]:
# Te mostre que una posible pseudoinversa es la obtenida por SVD, pero existen otras
# Veamos otra forma (A.T A)_inv * A.T

A_pse2 = np.linalg.inv(A.T.dot(A)).dot(A.T)
print(A_pse2)

# En este caso el resultado es el mismo

[[ 0.16666667 -0.10606061  0.03030303]
 [-0.16666667  0.28787879  0.06060606]]
