In [1]:
a=5
b=6
a+b

11

In [2]:
a=[5]
b=[6]
a+b

[5, 6]

In [3]:
import numpy as np

In [4]:
a=np.array([5])
b=np.array([6])
a+b

array([11])

In [5]:
a=np.array([1,2])
b=np.array([3,4])
a+b

array([4, 6])

In [6]:
a=np.ones(6)
a

array([1., 1., 1., 1., 1., 1.])

In [7]:
b=np.ones(6)*10
b

array([10., 10., 10., 10., 10., 10.])

In [8]:
a=np.array([1,2,3])
b=np.array([4,6])
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [9]:
a=np.array([[1,3],[5,8]])
print(a)

[[1 3]
 [5 8]]


In [10]:
b=np.array([3,2])

In [11]:
print(b)

[3 2]


In [12]:
a*b

array([[ 3,  6],
       [15, 16]])

In [13]:
c=np.dot(a,b)
print(c)

[ 9 31]


In [14]:
np.shape(c)


(2,)

In [15]:
np.shape(a)

(2, 2)