In [1]:
import numpy as np

In [2]:
A=np.array([[2,-1,1],[5,-4,2],[-1,-1,-1]])
print(A)

[[ 2 -1  1]
 [ 5 -4  2]
 [-1 -1 -1]]


In [15]:
A = np.array([[3,1,4],[2,1,3],[-1,-1,-1]])
A_inv=np.linalg.inv(A)
b=np.transpose(np.array([3,1,6]))
x=np.dot(A_inv,b)
print(x)

[-3. -8.  5.]
