In [2]:
import numpy as np

In [9]:
# Escribamos nuevamente nuestros elementos y veamos como funciona el producto interno entre 2 matrices

A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
C = A.dot(B)
print("Forma de la matriz A", A.shape)
print("Forma de la matriz B", B.shape)
print("Forma de la matriz C",C.shape)
print(C)
C=np.dot(A,B)
print()
print(C)

Forma de la matriz A (4, 3)
Forma de la matriz B (3, 2)
Forma de la matriz C (4, 2)
[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [ ]:
# Describir como es el producto interno en caso de encontrarlo util